image: clojure:lein-alpine

stages:
- build
- test
- deploy

variables:
  LEIN_SNAPSHOTS_IN_RELEASE: "TRUE"

build:
  stage: build
  script:
    - lein clean
    - lein jar

test:
  stage: test
  script:
    - lein test

deploy:
  stage: deploy
  script:
    - echo "{:user {:deploy-repositories [[\"internal\" {:url \"${ARTIFACTORY_DEPLOY_REPOSITORY}\" :username :env/artifactory_user :password :env/artifactory_pw :sign-releases false :checksum :ignore}]]}}" > ~/.lein/profiles.clj
    - lein deploy internal
  only:
    - master

pages:
  stage: deploy
  script:
    - lein codox
    - rm -rf public
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
